### ISSUE TITLE
cni 配置缺失

### ISSUE THREAD

**Issue by kenwoodjw** [caicloud/kube-ladder#10]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
kube-ladder/tutorials/lab3-manual-installtion.md
少配置了cni，会导致kubelet启动报错
**What you expected to happen**:
增加如下配置
```
 mkdir -p /etc/cni/net.d/
 
cat <<EOF> /etc/cni/net.d/10-flannel.conf
{
"name": "cbr0",
"type": "flannel",
"delegate": {
"isDefaultGateway": true
}
} 
EOF
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by bbbmj** [comment]
部署完 flannel，flannel 会去刷的

**Comment by kenwoodjw** [comment]
我现在没法启动pod，貌似kubelet报错，failed to ensure node lease exists, will retry in 3.2s, error: leases.coordination.k8s.io "worker1" is forbidden: User "system:node:worker-1" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node。我还在看这个报错

**Comment by bbbmj** [comment]
> 我现在没法启动pod，貌似kubelet报错，failed to ensure node lease exists, will retry in 3.2s, error: leases.coordination.k8s.io "worker1" is forbidden: User "system:node:worker-1" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node。我还在看这个报错

解决了吗？

**Comment by bbbmj** [comment]
已在该 PR https://github.com/caicloud/kube-ladder/pull/29 解决
