### ISSUE TITLE
kubectl run 的背后流程中文版

### ISSUE THREAD

**Issue by yangchuansheng** [caicloud/kube-ladder#18]
你好，这是我翻译的 ”kubectl run 的背后流程“ 中文版，可以考虑收录：https://mp.weixin.qq.com/s/ctdvbasKE-vpLRxDJjwVMw

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1: 

/cc @ddysher @bbbmj 

Needs your advice

**Comment by ddysher** [comment]
lgtm

/assign @bbbmj

**Comment by bbbmj** [comment]
LGTM

@yangchuansheng 你可以贡献个 PR，方式以下两种选择一个。

1.  加个链接到 readme

或者

2. 文档转成 markdown 放到 `./docs` 下（需要你自己创建下目录，记得在文档中也要加上原链接）
