### ISSUE TITLE
k8s二进制安装缺少网络插件

### ISSUE THREAD

**Issue by billon379** [caicloud/kube-ladder#27]
mkdir -p /opt/cni/bin
cd /opt/cni/bin
wget https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz
tar -xzvf cni-plugins-amd64-v0.7.1.tgz 
rm -rf cni-plugins-amd64-v0.7.1.tgz

**Comment by bbbmj** [comment]
部署完 flannel，flannel 会去刷

**Comment by billon379** [comment]
> 部署完 flannel，flannel 会去刷

不行的，我用VM恢复初始重新安装了3次，一直报错：
8月 15 22:57:43 k8s-node01 kubelet[31332]: E0815 22:57:43.039401   31332 cni.go:352] Error deleting kube-system_coredns-797d65b84c-qrntb/cbd1d835c9d8352557d4309d5528846af93a159ac63671bcb693feadcad67cb2 from network flannel/cbr0: failed to find plugin "portmap" in path [/opt/cni/bin]
8月 15 22:57:43 k8s-node01 kubelet[31332]: E0815 22:57:43.039494   31332 cni.go:352] Error deleting kube-system_coredns-797d65b84c-hj6wm/73e3711fc319dcd811542c25490f2681e763c048795cbc2e6d295734a812b555 from network flannel/cbr0: failed to find plugin "portmap" in path [/opt/cni/bin]
8月 15 22:57:43 k8s-node01 kubelet[31332]: E0815 22:57:43.040242   31332 remote_runtime.go:128] StopPodSandbox "73e3711fc319dcd811542c25490f2681e763c048795cbc2e6d295734a812b555" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "coredns-797d65b84c-hj6wm_kube-system" network: failed to find plugin "portmap" in path [/opt/cni/bin]
8月 15 22:57:43 k8s-node01 kubelet[31332]: E0815 22:57:43.040295   31332 kuberuntime_manager.go:841] Failed to stop sandbox {"docker" "73e3711fc319dcd811542c25490f2681e763c048795cbc2e6d295734a812b555"}

因为本地根本就没有/opt/cni/bin这个目录。我的解决方法就是创建对应目录，然后把cni插件放进去，就OK了。

**Comment by ddysher** [comment]
close via #29 

/close
