### ISSUE TITLE
kubectl run 不会再创建deployment了。

### ISSUE THREAD

**Issue by h3z** [caicloud/kube-ladder#35]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
按照文档中的安装kubectl时，会安装最新的kubectl，而kubectl 1.18之后，链接中这一步里的`kubectl run`不再会创建deployment了。困扰了我很久，后来才找到了是版本原因。（而且官方--help里也还是说会创建deploymetn），修改一下吧，以免其他人踩坑。
https://github.com/caicloud/kube-ladder/blob/master/tutorials/lab2-application-and-service.md#create-deployment

**What you expected to happen**:
修改一下kubectl的安装，或者提示一下吧！

**How to reproduce it (as minimally and precisely as possible)**:
kubectl修改这个特性的pr。https://github.com/kubernetes/kubernetes/pull/87077

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
谢谢反馈，没有考虑到 generators 全被删掉了这个大改动

/cc @bbbmj

**Comment by RobertChou** [comment]
那kubectl run了以后还需要手动创建对象吗？比如rc或者deployment
