### ISSUE TITLE
Caicloud 招聘

### ISSUE THREAD

**Issue by vivianlyw** [caicloud/kube-ladder#9]
招聘岗位

> -   云平台软件工程师
> -   产品经理

工作地点：杭州，上海，成都，北京

* * * * *

**云平台软件工程师**

薪资：15k-40k

经验：1-3 年 /3-5 年 /5-10 年

学历：本科及以上

工作地点：杭州、上海、成都，北京

负责才云容器平台的各类后端系统和组件的设计、开发、维护工作；

**任职要求：**

-   1-3 年 /3-5 年 /5-10 年以上后端开发经验；
-   熟悉计算机体系结构、数据结构和算法、操作系统、数据库、网络等基础原理；
-   精通 Golang 或至少一类后端编程语言（ C++/JAVA/Python 等）且具备快速转向 Golang 的能力；
-   熟悉各类开源类库、数据库、中间件的开发使用；
-   有分布式的软件架构设计、开发和运维经验，能快速定位和调试问题；
-   有良好的测试习惯以保证高质量软件的产出；
-   优秀的沟通协作能力、分析解决问题能力和学习能力；
-   [加分项] 熟悉 docker、kubernetes 及相关云原生系统的优先；

* * * * *

**产品经理**

薪资：15k-40k

经验：1-3/3-5

学历：本科及以上

工作地点：杭州

-   参与云平台整体产品的策划，根据市场及用户反馈，制定产品线路、落实项目方案；
-   负责产品的生命周期管理，包括需求搜集、版本规划、设计研发、客户落地、持续运营、迭代改进产品等，达成业务目标；
-   同开发团队、销售团队、运营团队紧密合作，协调不同岗位人员的工作，推动产品发展；
-   参与产品的测试、验收，需要为产品的整体质量负责；
-   跟进产品关键数据指标，用户反馈，制定产品的迭代计划；

**任职要求：**

-   有产品经理相关经验，具有很强的责任心；
-   对云计算行业有较深刻理解、思维活跃、调理清晰，有较高的逻辑分析和理解能力；
-   良好的写作能力、书面交流能力、沟通能力、团队协作能力；
-   保持热情，在日常工作中始终保持积极主动的态度，抗压能力强；
-   熟悉虚拟化、网络、存储等云计算相关技术；
-   加分项：有 Docker 使用经验，熟悉 Kubernetes, Mesos 架构者优先考虑；有有良好英文读写能力者，优先考虑；

* * * * *

简历投递方式

网站： <https://caicloud.io/jobs>

邮箱： hr@caicloud.io

感谢阅读，期待加入

**Comment by bbbmj** [comment]
也可以投递简历到 <baomengjiang@caicloud.io> 获得内推资格 :octocat:

/meow
